fix: try rerun a workflow

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -3,7 +3,7 @@ name: dev-static-website
 on:
   push:
     branches:
-      - 'notnow'
+      - '**'
       - '!main'
 
       
@@ -32,6 +32,7 @@ jobs:
     - name: Get pnpm store directory
       shell: bash
       run: |
+        exit 1. # fail this workflow on purpose to test the retry workflow
         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
 
     - uses: actions/cache@v4
